# Generated by Django 3.0.4 on 2020-06-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgExam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ct',
            name='ctPercentage',
            field=models.PositiveIntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Examiner',
            field=models.CharField(max_length=50, null=True, verbose_name='Examiner Name'),
        ),
    ]
