# Generated by Django 3.0.4 on 2020-06-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgExam', '0003_auto_20200628_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='Group',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='Session',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='ExamID',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Exam ID'),
        ),
    ]
