# Generated by Django 3.0.4 on 2020-06-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgExam', '0004_auto_20200628_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ct',
            name='TotalMarks',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ct',
            name='isResultEntered',
            field=models.BooleanField(null=True),
        ),
    ]
