# Generated by Django 3.0.4 on 2020-06-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgExam', '0005_auto_20200628_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practical',
            name='PassMarks',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='practical',
            name='PracticalPercentage',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='practical',
            name='isResultEntered',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='termfinal',
            name='CQ',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='termfinal',
            name='MCQ',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='termfinal',
            name='PassMarksCQ',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='termfinal',
            name='PassMarksMCQ',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='termfinal',
            name='TermFinalPercentage',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='termfinal',
            name='TotalMarks',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='termfinal',
            name='isResultEntered',
            field=models.BooleanField(null=True),
        ),
    ]
