# Generated by Django 3.0.4 on 2020-06-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgExam', '0006_auto_20200628_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termfinal',
            name='PassMarksCQ',
        ),
        migrations.RemoveField(
            model_name='termfinal',
            name='PassMarksMCQ',
        ),
        migrations.AddField(
            model_name='termfinal',
            name='PassPercentage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
