# Generated by Django 3.0.6 on 2020-06-19 20:08

import clgStudent.models
import clgStudent.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('Roll', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='College Roll')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
                ('Group', models.CharField(blank=True, choices=[('S', 'Science'), ('A', 'Arts'), ('C', 'Commerce')], max_length=1, null=True)),
                ('Father_Name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Father's Name")),
                ('Mother_Name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Mother's Name")),
                ('DOB', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('Guardian_Mobile_No', models.CharField(blank=True, max_length=14, null=True)),
                ('Session', models.PositiveIntegerField(null=True)),
                ('YearStatus', models.CharField(blank=True, choices=[('1', 'First Year'), ('2', 'Second Year'), ('P', 'Test Passed')], default='1', max_length=1, null=True)),
                ('Password', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=clgStudent.models.path_and_rename, validators=[clgStudent.validators.validate_file_size])),
                ('user_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Roll'],
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('Sub_Code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Subject Code')),
                ('Sub_Name', models.CharField(max_length=50)),
                ('ScienceType', models.CharField(choices=[('C', 'Compulsory'), ('O', 'Optional'), ('B', 'Compulsory & Optional'), ('X', '--')], default='X', max_length=1, verbose_name='Science Type')),
                ('ArtsType', models.CharField(choices=[('C', 'Compulsory'), ('O', 'Optional'), ('B', 'Compulsory & Optional'), ('X', '--')], default='X', max_length=1, verbose_name='Arts Type')),
                ('CommerceType', models.CharField(choices=[('C', 'Compulsory'), ('O', 'Optional'), ('B', 'Compulsory & Optional'), ('X', '--')], default='X', max_length=1, verbose_name='Commerce Type')),
            ],
            options={
                'ordering': ['Sub_Code'],
            },
        ),
        migrations.CreateModel(
            name='BoardResult',
            fields=[
                ('Roll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clgStudent.StudentInfo', verbose_name='College Roll')),
                ('Registration_No', models.IntegerField(unique=True, verbose_name='Registration No')),
                ('SSC_Roll', models.PositiveIntegerField(verbose_name='SSC Roll')),
                ('SSC_Board', models.CharField(choices=[('1', 'Dhaka'), ('2', 'Chittagong'), ('3', 'Comilla'), ('4', 'Rajshahi'), ('5', 'Khulna'), ('6', 'Rajshahi'), ('7', 'Barisal'), ('8', 'Dinajpur'), ('9', 'Others')], max_length=1, verbose_name='SSC Board')),
                ('SSC_Gpa', models.FloatField(verbose_name='SSC GPA')),
                ('JSC_Gpa', models.FloatField(verbose_name='JSC GPA')),
            ],
            options={
                'ordering': ['Roll'],
            },
        ),

    ]
