# Generated by Django 3.0.6 on 2020-07-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clgStudent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjects',
            fields=[
                ('Roll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clgStudent.StudentInfo')),
                ('comSub_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com11', to='clgStudent.Subjects')),
                ('comSub_12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com12', to='clgStudent.Subjects')),
                ('comSub_21', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com21', to='clgStudent.Subjects')),
                ('comSub_22', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com22', to='clgStudent.Subjects')),
                ('comSub_31', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com31', to='clgStudent.Subjects')),
                ('comSub_32', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com32', to='clgStudent.Subjects')),
                ('opSub_11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='op12', to='clgStudent.Subjects')),
            ],
            options={
                'ordering': ['Roll'],
            },
        ),
    ]
