# Generated by Django 3.0.6 on 2020-07-09 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clgStudent', '0003_auto_20200710_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjects',
            name='opSub_12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op12', to='clgStudent.Subjects'),
        ),
        migrations.AlterField(
            model_name='studentsubjects',
            name='opSub_11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='op11', to='clgStudent.Subjects'),
        ),
    ]
